version: '3.3'

volumes:
  volume_db:
    driver: local
    name: volume_db
    driver_opts:
      type: none
      o: bind
      device: /home/ehosu/data/db
  volume_wordpress:
    driver: local
    name: volume_wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/ehosu/data/wordpress

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./srcs/requirements/nginx/
    volumes:
      - volume_wordpress:/var/www/html
    ports:
      - 443:443
    networks:
      - backend
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./srcs/requirements/mariadb/
    volumes:
      - volume_db:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    networks:
      - backend
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./srcs/requirements/wordpress/
    volumes:
      - volume_wordpress:/var/www/html:rw
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
